version: '3'
services:
    apache:
        build: .docker/apache
        container_name: resty_apache
        ports:
          - 8082:80
        volumes:
          - .docker/config/vhosts:/etc/apache2/sites-enabled
          - .:/home/wwwroot/sf4
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password"
        container_name: resty_mysql
        volumes:
            - .docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: resty
            MYSQL_USER: resty
            MYSQL_PASSWORD: resty

    php:
        build: .docker/php
        container_name: resty_php
        ports:
          - 47187:47187
        volumes:
          - .:/home/wwwroot/sf4
        environment:
          - maildev_host=sf4_maildev
        depends_on:
          - maildev
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: resty_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: resty_maildev
        ports:
          - 8001:80
